### ISSUE TITLE
Docs are not clear on which api token 

### ISSUE THREAD

**Issue by johntdyer** [stripe-contrib/pagerbot#21] opened 2015-03-25 17:06 UTC
Its not clear what type of API token you require.  The link on the home page does not appear to link to a specifics type.  It would be great if you could clarify which token you require.  Thanks

**Comment by macobo** [comment] 2015-03-25 23:55
Hi john, thanks for the notes!

The app needs 3 sorts of tokens if you are using pagerbot together with slack:
* Pagerduty API token to access their API - found at https://yourcompany.pagerduty.com/api_keys (need admin access for that)
* Slack API token, that is used to post messages to slack: https://api.slack.com/web
* Slack outgoing webhook token, used to make sure that incoming messages come from slack. These can be found by [creating a new outgoing webhook](https://my.slack.com/services/new/outgoing-webhook)

The links in the pagerbot admin UI are currently wrong - sorry about that (since releasing, there's been some redesigning going on). 

Let me know if this helps or if you have any additional questions!

**Comment by johntdyer** [comment] 2015-03-27 15:05
Great, thanks helped.  You guys planning on updating the docs?

**Comment by macobo** [comment] 2015-03-27 15:48
Yup, just a question of time. It's a problem of incentives, as it's not very rewarding polishing the setup phase of the flow.

**Comment by shedd** [comment] 2015-11-11 18:04
+1 - the Slack API key was specifically unclear

**Comment by xaviershay** [comment] 2016-05-16 17:52
So I think maybe the slack OAuth 2 stuff is new since these docs/issue were written.

I've confirmed that you can use a "testing token" in order to verify pagerbot will work, but haven't yet investigated what is required to do a proper oauth integration.

**Comment by dbenamy** [comment] 2016-12-02 03:50
For what it's worth what I recently set it up, the latest docs all made perfect sense (other than the v1/v2 key which I have a pr for).

**Comment by macobo** [comment] 2017-01-12 22:43
:+1: Hopefully this is completely fixed now. Thanks @dbenamy and others for contributing!

**Closed by macobo** 2017-01-12 22:43 UTC
Labels: question
